/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrademarkRegistrationJammuRouteImport } from './routes/trademark-registration-jammu'
import { Route as TdsReturnFilingJammuRouteImport } from './routes/tds-return-filing-jammu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RocComplianceJammuRouteImport } from './routes/roc-compliance-jammu'
import { Route as PsaraRegistrationJammuRouteImport } from './routes/psara-registration-jammu'
import { Route as MsmeRegistrationJammuRouteImport } from './routes/msme-registration-jammu'
import { Route as LlpRegistrationJammuRouteImport } from './routes/llp-registration-jammu'
import { Route as IncomeTaxReturnFilingJammuRouteImport } from './routes/income-tax-return-filing-jammu'
import { Route as GstReturnFilingJammuRouteImport } from './routes/gst-return-filing-jammu'
import { Route as GstRegistrationJammuRouteImport } from './routes/gst-registration-jammu'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRegistrationJammuRouteImport } from './routes/company-registration-jammu'
import { Route as AuditServicesJammuRouteImport } from './routes/audit-services-jammu'
import { Route as AccountingBookkeepingJammuRouteImport } from './routes/accounting-bookkeeping-jammu'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const TrademarkRegistrationJammuRoute =
  TrademarkRegistrationJammuRouteImport.update({
    id: '/trademark-registration-jammu',
    path: '/trademark-registration-jammu',
    getParentRoute: () => rootRouteImport,
  } as any)
const TdsReturnFilingJammuRoute = TdsReturnFilingJammuRouteImport.update({
  id: '/tds-return-filing-jammu',
  path: '/tds-return-filing-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RocComplianceJammuRoute = RocComplianceJammuRouteImport.update({
  id: '/roc-compliance-jammu',
  path: '/roc-compliance-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const PsaraRegistrationJammuRoute = PsaraRegistrationJammuRouteImport.update({
  id: '/psara-registration-jammu',
  path: '/psara-registration-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const MsmeRegistrationJammuRoute = MsmeRegistrationJammuRouteImport.update({
  id: '/msme-registration-jammu',
  path: '/msme-registration-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const LlpRegistrationJammuRoute = LlpRegistrationJammuRouteImport.update({
  id: '/llp-registration-jammu',
  path: '/llp-registration-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeTaxReturnFilingJammuRoute =
  IncomeTaxReturnFilingJammuRouteImport.update({
    id: '/income-tax-return-filing-jammu',
    path: '/income-tax-return-filing-jammu',
    getParentRoute: () => rootRouteImport,
  } as any)
const GstReturnFilingJammuRoute = GstReturnFilingJammuRouteImport.update({
  id: '/gst-return-filing-jammu',
  path: '/gst-return-filing-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRegistrationJammuRoute = GstRegistrationJammuRouteImport.update({
  id: '/gst-registration-jammu',
  path: '/gst-registration-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRegistrationJammuRoute =
  CompanyRegistrationJammuRouteImport.update({
    id: '/company-registration-jammu',
    path: '/company-registration-jammu',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuditServicesJammuRoute = AuditServicesJammuRouteImport.update({
  id: '/audit-services-jammu',
  path: '/audit-services-jammu',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingBookkeepingJammuRoute =
  AccountingBookkeepingJammuRouteImport.update({
    id: '/accounting-bookkeeping-jammu',
    path: '/accounting-bookkeeping-jammu',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting-bookkeeping-jammu': typeof AccountingBookkeepingJammuRoute
  '/audit-services-jammu': typeof AuditServicesJammuRoute
  '/company-registration-jammu': typeof CompanyRegistrationJammuRoute
  '/contact': typeof ContactRoute
  '/gst-registration-jammu': typeof GstRegistrationJammuRoute
  '/gst-return-filing-jammu': typeof GstReturnFilingJammuRoute
  '/income-tax-return-filing-jammu': typeof IncomeTaxReturnFilingJammuRoute
  '/llp-registration-jammu': typeof LlpRegistrationJammuRoute
  '/msme-registration-jammu': typeof MsmeRegistrationJammuRoute
  '/psara-registration-jammu': typeof PsaraRegistrationJammuRoute
  '/roc-compliance-jammu': typeof RocComplianceJammuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tds-return-filing-jammu': typeof TdsReturnFilingJammuRoute
  '/trademark-registration-jammu': typeof TrademarkRegistrationJammuRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting-bookkeeping-jammu': typeof AccountingBookkeepingJammuRoute
  '/audit-services-jammu': typeof AuditServicesJammuRoute
  '/company-registration-jammu': typeof CompanyRegistrationJammuRoute
  '/contact': typeof ContactRoute
  '/gst-registration-jammu': typeof GstRegistrationJammuRoute
  '/gst-return-filing-jammu': typeof GstReturnFilingJammuRoute
  '/income-tax-return-filing-jammu': typeof IncomeTaxReturnFilingJammuRoute
  '/llp-registration-jammu': typeof LlpRegistrationJammuRoute
  '/msme-registration-jammu': typeof MsmeRegistrationJammuRoute
  '/psara-registration-jammu': typeof PsaraRegistrationJammuRoute
  '/roc-compliance-jammu': typeof RocComplianceJammuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tds-return-filing-jammu': typeof TdsReturnFilingJammuRoute
  '/trademark-registration-jammu': typeof TrademarkRegistrationJammuRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting-bookkeeping-jammu': typeof AccountingBookkeepingJammuRoute
  '/audit-services-jammu': typeof AuditServicesJammuRoute
  '/company-registration-jammu': typeof CompanyRegistrationJammuRoute
  '/contact': typeof ContactRoute
  '/gst-registration-jammu': typeof GstRegistrationJammuRoute
  '/gst-return-filing-jammu': typeof GstReturnFilingJammuRoute
  '/income-tax-return-filing-jammu': typeof IncomeTaxReturnFilingJammuRoute
  '/llp-registration-jammu': typeof LlpRegistrationJammuRoute
  '/msme-registration-jammu': typeof MsmeRegistrationJammuRoute
  '/psara-registration-jammu': typeof PsaraRegistrationJammuRoute
  '/roc-compliance-jammu': typeof RocComplianceJammuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tds-return-filing-jammu': typeof TdsReturnFilingJammuRoute
  '/trademark-registration-jammu': typeof TrademarkRegistrationJammuRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounting-bookkeeping-jammu'
    | '/audit-services-jammu'
    | '/company-registration-jammu'
    | '/contact'
    | '/gst-registration-jammu'
    | '/gst-return-filing-jammu'
    | '/income-tax-return-filing-jammu'
    | '/llp-registration-jammu'
    | '/msme-registration-jammu'
    | '/psara-registration-jammu'
    | '/roc-compliance-jammu'
    | '/sitemap.xml'
    | '/tds-return-filing-jammu'
    | '/trademark-registration-jammu'
    | '/services/$slug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounting-bookkeeping-jammu'
    | '/audit-services-jammu'
    | '/company-registration-jammu'
    | '/contact'
    | '/gst-registration-jammu'
    | '/gst-return-filing-jammu'
    | '/income-tax-return-filing-jammu'
    | '/llp-registration-jammu'
    | '/msme-registration-jammu'
    | '/psara-registration-jammu'
    | '/roc-compliance-jammu'
    | '/sitemap.xml'
    | '/tds-return-filing-jammu'
    | '/trademark-registration-jammu'
    | '/services/$slug'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounting-bookkeeping-jammu'
    | '/audit-services-jammu'
    | '/company-registration-jammu'
    | '/contact'
    | '/gst-registration-jammu'
    | '/gst-return-filing-jammu'
    | '/income-tax-return-filing-jammu'
    | '/llp-registration-jammu'
    | '/msme-registration-jammu'
    | '/psara-registration-jammu'
    | '/roc-compliance-jammu'
    | '/sitemap.xml'
    | '/tds-return-filing-jammu'
    | '/trademark-registration-jammu'
    | '/services/$slug'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountingBookkeepingJammuRoute: typeof AccountingBookkeepingJammuRoute
  AuditServicesJammuRoute: typeof AuditServicesJammuRoute
  CompanyRegistrationJammuRoute: typeof CompanyRegistrationJammuRoute
  ContactRoute: typeof ContactRoute
  GstRegistrationJammuRoute: typeof GstRegistrationJammuRoute
  GstReturnFilingJammuRoute: typeof GstReturnFilingJammuRoute
  IncomeTaxReturnFilingJammuRoute: typeof IncomeTaxReturnFilingJammuRoute
  LlpRegistrationJammuRoute: typeof LlpRegistrationJammuRoute
  MsmeRegistrationJammuRoute: typeof MsmeRegistrationJammuRoute
  PsaraRegistrationJammuRoute: typeof PsaraRegistrationJammuRoute
  RocComplianceJammuRoute: typeof RocComplianceJammuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TdsReturnFilingJammuRoute: typeof TdsReturnFilingJammuRoute
  TrademarkRegistrationJammuRoute: typeof TrademarkRegistrationJammuRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trademark-registration-jammu': {
      id: '/trademark-registration-jammu'
      path: '/trademark-registration-jammu'
      fullPath: '/trademark-registration-jammu'
      preLoaderRoute: typeof TrademarkRegistrationJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tds-return-filing-jammu': {
      id: '/tds-return-filing-jammu'
      path: '/tds-return-filing-jammu'
      fullPath: '/tds-return-filing-jammu'
      preLoaderRoute: typeof TdsReturnFilingJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roc-compliance-jammu': {
      id: '/roc-compliance-jammu'
      path: '/roc-compliance-jammu'
      fullPath: '/roc-compliance-jammu'
      preLoaderRoute: typeof RocComplianceJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psara-registration-jammu': {
      id: '/psara-registration-jammu'
      path: '/psara-registration-jammu'
      fullPath: '/psara-registration-jammu'
      preLoaderRoute: typeof PsaraRegistrationJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msme-registration-jammu': {
      id: '/msme-registration-jammu'
      path: '/msme-registration-jammu'
      fullPath: '/msme-registration-jammu'
      preLoaderRoute: typeof MsmeRegistrationJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llp-registration-jammu': {
      id: '/llp-registration-jammu'
      path: '/llp-registration-jammu'
      fullPath: '/llp-registration-jammu'
      preLoaderRoute: typeof LlpRegistrationJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-tax-return-filing-jammu': {
      id: '/income-tax-return-filing-jammu'
      path: '/income-tax-return-filing-jammu'
      fullPath: '/income-tax-return-filing-jammu'
      preLoaderRoute: typeof IncomeTaxReturnFilingJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-return-filing-jammu': {
      id: '/gst-return-filing-jammu'
      path: '/gst-return-filing-jammu'
      fullPath: '/gst-return-filing-jammu'
      preLoaderRoute: typeof GstReturnFilingJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-registration-jammu': {
      id: '/gst-registration-jammu'
      path: '/gst-registration-jammu'
      fullPath: '/gst-registration-jammu'
      preLoaderRoute: typeof GstRegistrationJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-registration-jammu': {
      id: '/company-registration-jammu'
      path: '/company-registration-jammu'
      fullPath: '/company-registration-jammu'
      preLoaderRoute: typeof CompanyRegistrationJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-services-jammu': {
      id: '/audit-services-jammu'
      path: '/audit-services-jammu'
      fullPath: '/audit-services-jammu'
      preLoaderRoute: typeof AuditServicesJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-bookkeeping-jammu': {
      id: '/accounting-bookkeeping-jammu'
      path: '/accounting-bookkeeping-jammu'
      fullPath: '/accounting-bookkeeping-jammu'
      preLoaderRoute: typeof AccountingBookkeepingJammuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountingBookkeepingJammuRoute: AccountingBookkeepingJammuRoute,
  AuditServicesJammuRoute: AuditServicesJammuRoute,
  CompanyRegistrationJammuRoute: CompanyRegistrationJammuRoute,
  ContactRoute: ContactRoute,
  GstRegistrationJammuRoute: GstRegistrationJammuRoute,
  GstReturnFilingJammuRoute: GstReturnFilingJammuRoute,
  IncomeTaxReturnFilingJammuRoute: IncomeTaxReturnFilingJammuRoute,
  LlpRegistrationJammuRoute: LlpRegistrationJammuRoute,
  MsmeRegistrationJammuRoute: MsmeRegistrationJammuRoute,
  PsaraRegistrationJammuRoute: PsaraRegistrationJammuRoute,
  RocComplianceJammuRoute: RocComplianceJammuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TdsReturnFilingJammuRoute: TdsReturnFilingJammuRoute,
  TrademarkRegistrationJammuRoute: TrademarkRegistrationJammuRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
